### PR TITLE
added docs for grafana/prometheus steps

### PR DESCRIPTION
**Pull request by dgrisham**
I added some documentation reflecting the steps I had to take in order to get Grafana/Prometheus to work locally for me. Also, there are a lot of changes because I reformatted the README for my own editing purposes -- sorry if that's bad practice/annoying.

**Commit message(s)**:

added docs for grafana/prometheus steps

Added minimum necessary steps for users to access Grafana/Prometheus for metrics
and visualization.

---

updated prometheus manifests, set default grafana vars for local use

Updated the prometheus manifests by copying the newer version of the file from
the original source. I also changed a couple of the default values to reflect
the recommendations made in the Grafana/Prometheus steps in the readme, which
make it easier to access Grafana locally (by removing authentication; users can
add this if they need it).

### CODE REVIEW

**Comment by hsanjuan** [comment]
Does anything need to change in order to use the ipfs-cluster tests with prometheus? It's not clear to me how prometheus is launched, but maybe I'm missing something...

**Comment by dgrisham** [comment]
@hsanjuan The minimum change is simply to un-comment [this line in the ipfs-cluster `init.sh`](https://github.com/ipfs/kubernetes-ipfs/blob/master/ipfs-cluster/init.sh#L6). Then, when you run `init.sh`, it will create the Prometheus/Grafana pods which will gather metrics for you. Then you can view the plots on Grafana by telling Kubernetes to forward connections on one of your local ports to the port on the Grafana pod that's hosting the Grafana UI.

Does that answer your question/make sense?

**Comment by hsanjuan** [comment]
@dgrisham then, uncomment it in this PR too :)

Can you add some echo statements at the end of `init.sh` with the commands that need to run to get access to monitoring. It's nice to have the script print something like:

```
ipfs-cluster ready to run tests.

For viewing monitoring metrics in graphana run the following commands:

a
b
c
```

**Comment by dgrisham** [comment]
@hsanjuan Gotcha, both of those changes have been made + pushed!

**Comment by hsanjuan** [comment]
@FrankPetrilli this looks good to me. Do you want to look/merge ?

Thanks!

**Comment by FrankPetrilli** [comment]
I'm good with all the changes; I'll definitely merge. Thanks!

**Pull request merged**
